name: Visualize repo with diagram

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  visualize_repo:
    permissions:
      contents: write  # for githubocto/repo-visualizer to commit and push diagrams
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: develop
          token: ${{ secrets.REPO_TOKEN }}
        
      - name: Update diagram
        uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # ratchet:githubocto/repo-visualizer@v0.9.1
        with:
          excluded_paths: ".github,.husky,.yarn"
