name: Visualize repo with diagram

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  visualize_repo:
    permissions:
      contents: write  # for githubocto/repo-visualizer to commit and push diagrams
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          ref: develop
          token: ${{ secrets.REPO_TOKEN }}
        
      - name: Update diagram
        uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # ratchet:githubocto/repo-visualizer@v0.9.1
        with:
          excluded_paths: ".github,.husky,.yarn"
